Add scope to package name
The name "jspaint" is not taken on npm, but it's unavailable, because
npm restricts package names that are too similar to existing packages.

This breaks the Electron Forge build on Ubuntu:
                                                                                                                              
    > @1j01/jspaint@1.0.0 electron:make                                                                                       
    > electron-forge make                                                                                                     
                                                                                                                              
    ✔ Checking your system
    ✔ Loading configuration
    ✔ Resolving make targets
      › Making for the following targets: , 
    ✔ Running package command
      ✔ Preparing to package application
      ✔ Running packaging hooks
        ✔ Running generateAssets hook
        ✔ Running prePackage hook
      ✔ Packaging application
        ✔ Packaging for x64 on linux [11s]
      ✔ Running postPackage hook
    ✔ Running preMake hook
    ❯ Making distributables
      ✖ Making a deb distributable for linux/x64
        › could not find the Electron app binary at "/home/io/Projects/jspaint/out/JS Paint-linux-x64/@1j01/jspaint". You m…
      ✖ Making a rpm distributable for linux/x64
    ◼ Running postMake hook

    An unhandled rejection has occurred inside Forge:
    Error: could not find the Electron app binary at "/home/io/Projects/jspaint/out/JS Paint-linux-x64/@1j01/jspaint". You may need to re-bundle the app using Electron Packager's "executableName" option.
    at /home/io/Projects/jspaint/node_modules/electron-installer-common/src/installer.js:154:15
        at async Promise.all (index 3)
        at async module.exports (/home/io/Projects/jspaint/node_modules/electron-installer-debian/src/installer.js:261:3)
        at async MakerDeb.make (/home/io/Projects/jspaint/node_modules/@electron-forge/maker-deb/dist/MakerDeb.js:39:34)
        at async /home/io/Projects/jspaint/node_modules/@electron-forge/core/dist/api/make.js:187:55
        at async Task.task (/home/io/Projects/jspaint/node_modules/@electron-forge/tracer/dist/index.js:58:20)
        at async Task.run (/home/io/Projects/jspaint/node_modules/listr2/dist/index.cjs:978:11)
        at async /home/io/Projects/jspaint/node_modules/listr2/node_modules/p-map/index.js:57:22

even though I have set "executableName", and set it how I want it.