Fix format selection when saving a palette with FS Access API
Fix error when saving a file from Colors > Save Colors, when
`enable_fs_access_api` is set to true, in supporting browsers:

    TypeError: Failed to execute 'showSaveFilePicker' on 'Window': Invalid type: undefined

`format.mimeType` is what it's referring to that's undefined, as the
palette file formats don't have defined MIME media types.

Also fix type errors from strict @types/wicg-file-system-access which
uses string template literal types.