Declare global `loaded_localizations`
Fixes the error:

  src/app-localization.js:1108:9 - error TS2339: Property 'loaded_localizations' does not exist on type 'Window & typeof globalThis'.
  
  1108  window.loaded_localizations = function loaded_localizations(language, mapping) {
               ~~~~~~~~~~~~~~~~~~~~