Fix tests??????????
It gave this error (AND OR SOMETHING SIMILAR BUT FOR STATUS BAR):

    CypressError: Timed out retrying: `cy.click()` failed because this element is not visible:

    `<tr class="menu-row menu-item" tabindex="-1">...</tr>`

    This element `<tr.menu-row.menu-item>` is not visible because its parent `<div.menu-popup>` has CSS property: `display: none`

    Fix this problem, or use `{force: true}` to disable error checking.

    https://on.cypress.io/element-cannot-be-interacted-with

I don't know when this started happening, but it makes sense that the status text might be empty sometimes and thus zero-width.

As for it failing to click on a popup, well, that's more complicated.