Fix error after palette is rerendered
In cases where the palette is rerendered - switching themes, toggling vertical color box mode, loading a palette, etc.,
a leaked event listener or other places could throw an error similar to:

    Uncaught TypeError: $foreground_color.data(...) is not a function

- If you opened the Edit Colors dialog, but changed the UI theme before hitting OK, it would fail to update the color or close the dialog. This is fixed. It now uses an index into the palette so it even works if you change the palette completely while the dialog is open. Differently sized palettes are also handled.
- If you opened the Edit Colors dialog, but switched to monochrome mode in Image > Attributes before hitting OK, it would partially fail to update the color - it would visually change the color cell, but if you selected it, it would select the old pattern. This is fixed.
- If you toggled Vertical Color Box mode, the palette broke - you could no longer select colors. This is fixed.
- I haven't fixed the event listener leak itself.