Fix error handling when setting wallpaper
It got this error message in the electron app despite success:

    Failed to set wallpaper.

    Error: Error invoking remote method 'set-wallpaper': reply was never sent
        at o.invoke (node:electron/js2c/sandbox_bundle:29:551)

The "wallpaper" module's API changed more than I thought.
It was converted to use promises in this commit:
https://github.com/sindresorhus/wallpaper/commit/4d1dbc3e582328cb1e0da65b94ebe6191f73bbe5
It's easy to see how I missed this: the project has no changelog.
There's some GitHub releases with notes, but they don't go back that far.

Broken in "Implement centered wallpaper" (https://github.com/1j01/jspaint/commit/211fb90a99711d755108cef97c521a971d02edb3)
theoretically.