Fix TypeScript error about getFile not existing
This error was shown because getFile is a method of the more specific
type FileSystemFileHandle, not the base FileSystemHandle:

    src/app.js:844:29 - error TS2339: Property 'getFile' does not exist on type 'FileSystemHandle'.

    844         file = await handle.getFile();
                                    ~~~~~~~

    Found 1 error in src/app.js:844

Use instanceof for type narrowing.

Back down to zero errors!