Fix TS not finding module 'electron'
Fixes the error:

  src/electron-injected.js:11:52 - error TS2792: Cannot find module 'electron'. Did you mean to set the 'moduleResolution' option to 'nodenext', or to add aliases to the 'paths' option?
  
  11 const { /*contextBridge,*/ ipcRenderer } = require('electron');
                                                        ~~~~~~~~~~